name: k8s Pipeline

on:
  push:
    branches:
      - main  # Or your desired deployment branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3\

        # Add Prometheus and Grafana Setup Steps
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Add Prometheus Helm Repository
        run: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

      - name: Update Helm Repositories
        run: helm repo update

      - name: Install Prometheus Operator
        run: helm install prometheus prometheus-community/kube-prometheus-stack --create-namespace -n monitoring

      - name: Install Grafana
        run: helm install grafana grafana/grafana -n monitoring --set "service.type=LoadBalancer" --set persistence.enabled=false
    
      - name: Deploy to AWS EKS
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}
          kubectl apply -f frontend_deployment.yaml
          kubectl apply -f backend.yaml
          kubectl apply -f database.yaml   
          kubectl apply -f secret.yaml
          kubectl apply -f service.yaml